name = "nm7-fpt-event-watchdog"
main = "src/index.js"
compatibility_date = "2026-09-25"
workers_dev = true

# Production secret GITHUB_TOKEN is managed in Cloudflare Worker settings.

[triggers]
crons = ["*/5 * * * *"]
